// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBnQfAV_YETeky6gv3dUWcNn8gy7FbQE',
    appId: '1:405150164170:web:201286b798d271666f4033',
    messagingSenderId: '405150164170',
    projectId: 'e-bib-5d3a4',
    authDomain: 'e-bib-5d3a4.firebaseapp.com',
    storageBucket: 'e-bib-5d3a4.appspot.com',
    measurementId: 'G-HJT8C24TZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9x2j0LZroW4iMPxjNmgxqNSmunIQUs8',
    appId: '1:405150164170:android:e39d7a8e6d0165656f4033',
    messagingSenderId: '405150164170',
    projectId: 'e-bib-5d3a4',
    storageBucket: 'e-bib-5d3a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0O3xLMPGKBcYGfJ_ClHew4Zl0d-M1Hbc',
    appId: '1:405150164170:ios:2a75fe62971276a56f4033',
    messagingSenderId: '405150164170',
    projectId: 'e-bib-5d3a4',
    storageBucket: 'e-bib-5d3a4.appspot.com',
    iosClientId: '405150164170-0402fjbj49ngiijkufteegb1sp44g06r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0O3xLMPGKBcYGfJ_ClHew4Zl0d-M1Hbc',
    appId: '1:405150164170:ios:8c86e9daa04438666f4033',
    messagingSenderId: '405150164170',
    projectId: 'e-bib-5d3a4',
    storageBucket: 'e-bib-5d3a4.appspot.com',
    iosClientId: '405150164170-h05mc74jc8jl2ruf4f90onodqfspfmne.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebib.RunnerTests',
  );
}
